name: Run lint on pull requests
on:
  pull_request:
    branches: [ uat ]

jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: 'stable'

      - name: Install packages
        run: flutter pub get

      - name: Linter
        run: flutter analyze

      # - name: Test
      #   run: flutter test